Predicted_Labels = zeros(1,1500)
Sum = 0;

%% Classifying the test dataset using the generated training model variables 
for i=1:1500
    if (X_test(i,:)*w+b) > 0
        Predicted_Labels(i) = 1;
    else
        Predicted_Labels(i) = -1;
    end
end

%% Comparing the y labels generated by my model to the predefined y labels in y_test table
for i=1:1500
    if Predicted_Labels(i) == y_test(i)
        Sum = Sum + 1;
    end
end

%% Checking for Correctness 
test_accuracy = Sum/1500;