[row,col] = size(X_training);

w_dual = zeros(col,1);
b_dual = 0;


for o=1:row
    w_dual = w_dual + al(o,1)*y_training(o)*X_training(o,:)';
end

for o=1:row
    b_dual = b_dual + (1/row)*(y_training(o)-w_dual'*X_training(o,:)');
end

Predicted_dual_labels = zeros(1,1500);

dual_Sum = 0;

%% Classifying the test dataset using the training model variables 
for x=1:1500
    if (X_test(x,:)*w_dual+b_dual) > 0
        Predicted_dual_labels(x) = 1;
    else
        Predicted_dual_labels(x) = -1;
    end
end

%% Comparing the y labels generated by my model to the predefined y labels in y_test table
for x=1:1500
    if Predicted_dual_labels(x) == y_test(x)
        dual_Sum = dual_Sum + 1;
    end
end

%% Checking for Correctness 
test = dual_Sum/1500;
